// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// clang-format off
// source: messages-ethereum-onekey.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

#import "MessagesCommon.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class EthereumSignTxEIP1559OneKey_EthereumAccessListOneKey;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MessagesEthereumOnekeyRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface MessagesEthereumOnekeyRoot : GPBRootObject
@end

#pragma mark - EthereumGetPublicKeyOneKey

typedef GPB_ENUM(EthereumGetPublicKeyOneKey_FieldNumber) {
  EthereumGetPublicKeyOneKey_FieldNumber_AddressNArray = 1,
  EthereumGetPublicKeyOneKey_FieldNumber_ShowDisplay = 2,
  EthereumGetPublicKeyOneKey_FieldNumber_ChainId = 3,
};

/**
 * *
 * Request: Ask device for public key corresponding to address_n path
 * \@start
 * \@next EthereumGetPublicKeyOneKey
 * \@next Failure
 **/
GPB_FINAL @interface EthereumGetPublicKeyOneKey : GPBMessage

/** BIP-32 path to derive the key from master node */
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *addressNArray;
/** The number of items in @c addressNArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger addressNArray_Count;

/** optionally show on display before sending the result */
@property(nonatomic, readwrite) BOOL showDisplay;
@property(nonatomic, readwrite) BOOL hasShowDisplay;

/** used to personalized display */
@property(nonatomic, readwrite) uint64_t chainId;
@property(nonatomic, readwrite) BOOL hasChainId;

@end

#pragma mark - EthereumPublicKeyOneKey

typedef GPB_ENUM(EthereumPublicKeyOneKey_FieldNumber) {
  EthereumPublicKeyOneKey_FieldNumber_Node = 1,
  EthereumPublicKeyOneKey_FieldNumber_Xpub = 2,
};

/**
 * *
 * Response: Contains public key derived from device private seed
 * \@end
 **/
GPB_FINAL @interface EthereumPublicKeyOneKey : GPBMessage

/** BIP32 public node */
@property(nonatomic, readwrite, strong, null_resettable) HDNodeType *node;
/** Test to see if @c node has been set. */
@property(nonatomic, readwrite) BOOL hasNode;

/** serialized form of public node */
@property(nonatomic, readwrite, copy, null_resettable) NSString *xpub;
/** Test to see if @c xpub has been set. */
@property(nonatomic, readwrite) BOOL hasXpub;

@end

#pragma mark - EthereumGetAddressOneKey

typedef GPB_ENUM(EthereumGetAddressOneKey_FieldNumber) {
  EthereumGetAddressOneKey_FieldNumber_AddressNArray = 1,
  EthereumGetAddressOneKey_FieldNumber_ShowDisplay = 2,
  EthereumGetAddressOneKey_FieldNumber_ChainId = 3,
};

/**
 * *
 * Request: Ask device for Ethereum address corresponding to address_n path
 * \@start
 * \@next EthereumAddressOneKey
 * \@next Failure
 **/
GPB_FINAL @interface EthereumGetAddressOneKey : GPBMessage

/** BIP-32 path to derive the key from master node */
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *addressNArray;
/** The number of items in @c addressNArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger addressNArray_Count;

/** optionally show on display before sending the result */
@property(nonatomic, readwrite) BOOL showDisplay;
@property(nonatomic, readwrite) BOOL hasShowDisplay;

/** used to personalized display */
@property(nonatomic, readwrite) uint64_t chainId;
@property(nonatomic, readwrite) BOOL hasChainId;

@end

#pragma mark - EthereumAddressOneKey

typedef GPB_ENUM(EthereumAddressOneKey_FieldNumber) {
  EthereumAddressOneKey_FieldNumber_OldAddress = 1,
  EthereumAddressOneKey_FieldNumber_Address = 2,
};

/**
 * *
 * Response: Contains an Ethereum address derived from device private seed
 * \@end
 **/
GPB_FINAL @interface EthereumAddressOneKey : GPBMessage

/** trezor <1.8.0, <2.1.0 - raw bytes of Ethereum address */
@property(nonatomic, readwrite, copy, null_resettable) NSData *oldAddress GPB_DEPRECATED_MSG("hw.trezor.messages.ethereum_onekey.EthereumAddressOneKey._old_address is deprecated (see messages-ethereum-onekey.proto).");
/** Test to see if @c oldAddress has been set. */
@property(nonatomic, readwrite) BOOL hasOldAddress GPB_DEPRECATED_MSG("hw.trezor.messages.ethereum_onekey.EthereumAddressOneKey._old_address is deprecated (see messages-ethereum-onekey.proto).");

/** Ethereum address as hex-encoded string */
@property(nonatomic, readwrite, copy, null_resettable) NSString *address;
/** Test to see if @c address has been set. */
@property(nonatomic, readwrite) BOOL hasAddress;

@end

#pragma mark - EthereumSignTxOneKey

typedef GPB_ENUM(EthereumSignTxOneKey_FieldNumber) {
  EthereumSignTxOneKey_FieldNumber_AddressNArray = 1,
  EthereumSignTxOneKey_FieldNumber_Nonce = 2,
  EthereumSignTxOneKey_FieldNumber_GasPrice = 3,
  EthereumSignTxOneKey_FieldNumber_GasLimit = 4,
  EthereumSignTxOneKey_FieldNumber_Value = 6,
  EthereumSignTxOneKey_FieldNumber_DataInitialChunk = 7,
  EthereumSignTxOneKey_FieldNumber_DataLength = 8,
  EthereumSignTxOneKey_FieldNumber_ChainId = 9,
  EthereumSignTxOneKey_FieldNumber_TxType = 10,
  EthereumSignTxOneKey_FieldNumber_To = 11,
};

/**
 * *
 * Request: Ask device to sign transaction
 * gas_price, gas_limit and chain_id must be provided and non-zero.
 * All other fields are optional and default to value `0` if missing.
 * Note: the first at most 1024 bytes of data MUST be transmitted as part of this message.
 * \@start
 * \@next EthereumTxRequestOnekey
 * \@next Failure
 **/
GPB_FINAL @interface EthereumSignTxOneKey : GPBMessage

/** BIP-32 path to derive the key from master node */
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *addressNArray;
/** The number of items in @c addressNArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger addressNArray_Count;

/** <=256 bit unsigned big endian */
@property(nonatomic, readwrite, copy, null_resettable) NSData *nonce;
/** Test to see if @c nonce has been set. */
@property(nonatomic, readwrite) BOOL hasNonce;

/** <=256 bit unsigned big endian (in wei) */
@property(nonatomic, readwrite, copy, null_resettable) NSData *gasPrice;
/** Test to see if @c gasPrice has been set. */
@property(nonatomic, readwrite) BOOL hasGasPrice;

/** <=256 bit unsigned big endian */
@property(nonatomic, readwrite, copy, null_resettable) NSData *gasLimit;
/** Test to see if @c gasLimit has been set. */
@property(nonatomic, readwrite) BOOL hasGasLimit;

/** recipient address */
@property(nonatomic, readwrite, copy, null_resettable) NSString *to;
/** Test to see if @c to has been set. */
@property(nonatomic, readwrite) BOOL hasTo;

/** <=256 bit unsigned big endian (in wei) */
@property(nonatomic, readwrite, copy, null_resettable) NSData *value;
/** Test to see if @c value has been set. */
@property(nonatomic, readwrite) BOOL hasValue;

/** The initial data chunk (<= 1024 bytes) */
@property(nonatomic, readwrite, copy, null_resettable) NSData *dataInitialChunk;
/** Test to see if @c dataInitialChunk has been set. */
@property(nonatomic, readwrite) BOOL hasDataInitialChunk;

/** Length of transaction payload */
@property(nonatomic, readwrite) uint32_t dataLength;
@property(nonatomic, readwrite) BOOL hasDataLength;

/** Chain Id for EIP 155 */
@property(nonatomic, readwrite) uint64_t chainId;
@property(nonatomic, readwrite) BOOL hasChainId;

/** Used for Wanchain */
@property(nonatomic, readwrite) uint32_t txType;
@property(nonatomic, readwrite) BOOL hasTxType;

@end

#pragma mark - EthereumSignTxEIP1559OneKey

typedef GPB_ENUM(EthereumSignTxEIP1559OneKey_FieldNumber) {
  EthereumSignTxEIP1559OneKey_FieldNumber_AddressNArray = 1,
  EthereumSignTxEIP1559OneKey_FieldNumber_Nonce = 2,
  EthereumSignTxEIP1559OneKey_FieldNumber_MaxGasFee = 3,
  EthereumSignTxEIP1559OneKey_FieldNumber_MaxPriorityFee = 4,
  EthereumSignTxEIP1559OneKey_FieldNumber_GasLimit = 5,
  EthereumSignTxEIP1559OneKey_FieldNumber_To = 6,
  EthereumSignTxEIP1559OneKey_FieldNumber_Value = 7,
  EthereumSignTxEIP1559OneKey_FieldNumber_DataInitialChunk = 8,
  EthereumSignTxEIP1559OneKey_FieldNumber_DataLength = 9,
  EthereumSignTxEIP1559OneKey_FieldNumber_ChainId = 10,
  EthereumSignTxEIP1559OneKey_FieldNumber_AccessListArray = 11,
};

/**
 * *
 * Request: Ask device to sign EIP1559 transaction
 * Note: the first at most 1024 bytes of data MUST be transmitted as part of this message.
 * \@start
 * \@next EthereumTxRequestOneKey
 * \@next Failure
 **/
GPB_FINAL @interface EthereumSignTxEIP1559OneKey : GPBMessage

/** BIP-32 path to derive the key from master node */
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *addressNArray;
/** The number of items in @c addressNArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger addressNArray_Count;

/** <=256 bit unsigned big endian */
@property(nonatomic, readwrite, copy, null_resettable) NSData *nonce;
/** Test to see if @c nonce has been set. */
@property(nonatomic, readwrite) BOOL hasNonce;

/** <=256 bit unsigned big endian (in wei) */
@property(nonatomic, readwrite, copy, null_resettable) NSData *maxGasFee;
/** Test to see if @c maxGasFee has been set. */
@property(nonatomic, readwrite) BOOL hasMaxGasFee;

/** <=256 bit unsigned big endian (in wei) */
@property(nonatomic, readwrite, copy, null_resettable) NSData *maxPriorityFee;
/** Test to see if @c maxPriorityFee has been set. */
@property(nonatomic, readwrite) BOOL hasMaxPriorityFee;

/** <=256 bit unsigned big endian */
@property(nonatomic, readwrite, copy, null_resettable) NSData *gasLimit;
/** Test to see if @c gasLimit has been set. */
@property(nonatomic, readwrite) BOOL hasGasLimit;

/** recipient address */
@property(nonatomic, readwrite, copy, null_resettable) NSString *to;
/** Test to see if @c to has been set. */
@property(nonatomic, readwrite) BOOL hasTo;

/** <=256 bit unsigned big endian (in wei) */
@property(nonatomic, readwrite, copy, null_resettable) NSData *value;
/** Test to see if @c value has been set. */
@property(nonatomic, readwrite) BOOL hasValue;

/** The initial data chunk (<= 1024 bytes) */
@property(nonatomic, readwrite, copy, null_resettable) NSData *dataInitialChunk;
/** Test to see if @c dataInitialChunk has been set. */
@property(nonatomic, readwrite) BOOL hasDataInitialChunk;

/** Length of transaction payload */
@property(nonatomic, readwrite) uint32_t dataLength;
@property(nonatomic, readwrite) BOOL hasDataLength;

/** Chain Id for EIP 155 */
@property(nonatomic, readwrite) uint64_t chainId;
@property(nonatomic, readwrite) BOOL hasChainId;

/** Access List */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<EthereumSignTxEIP1559OneKey_EthereumAccessListOneKey*> *accessListArray;
/** The number of items in @c accessListArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger accessListArray_Count;

@end

#pragma mark - EthereumSignTxEIP1559OneKey_EthereumAccessListOneKey

typedef GPB_ENUM(EthereumSignTxEIP1559OneKey_EthereumAccessListOneKey_FieldNumber) {
  EthereumSignTxEIP1559OneKey_EthereumAccessListOneKey_FieldNumber_Address = 1,
  EthereumSignTxEIP1559OneKey_EthereumAccessListOneKey_FieldNumber_StorageKeysArray = 2,
};

GPB_FINAL @interface EthereumSignTxEIP1559OneKey_EthereumAccessListOneKey : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *address;
/** Test to see if @c address has been set. */
@property(nonatomic, readwrite) BOOL hasAddress;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSData*> *storageKeysArray;
/** The number of items in @c storageKeysArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger storageKeysArray_Count;

@end

#pragma mark - EthereumTxRequestOneKey

typedef GPB_ENUM(EthereumTxRequestOneKey_FieldNumber) {
  EthereumTxRequestOneKey_FieldNumber_DataLength = 1,
  EthereumTxRequestOneKey_FieldNumber_SignatureV = 2,
  EthereumTxRequestOneKey_FieldNumber_SignatureR = 3,
  EthereumTxRequestOneKey_FieldNumber_SignatureS = 4,
};

/**
 * *
 * Response: Device asks for more data from transaction payload, or returns the signature.
 * If data_length is set, device awaits that many more bytes of payload.
 * Otherwise, the signature_* fields contain the computed transaction signature. All three fields will be present.
 * \@end
 * \@next EthereumTxAckOneKey
 **/
GPB_FINAL @interface EthereumTxRequestOneKey : GPBMessage

/** Number of bytes being requested (<= 1024) */
@property(nonatomic, readwrite) uint32_t dataLength;
@property(nonatomic, readwrite) BOOL hasDataLength;

/** Computed signature (recovery parameter, limited to 27 or 28) */
@property(nonatomic, readwrite) uint32_t signatureV;
@property(nonatomic, readwrite) BOOL hasSignatureV;

/** Computed signature R component (256 bit) */
@property(nonatomic, readwrite, copy, null_resettable) NSData *signatureR;
/** Test to see if @c signatureR has been set. */
@property(nonatomic, readwrite) BOOL hasSignatureR;

/** Computed signature S component (256 bit) */
@property(nonatomic, readwrite, copy, null_resettable) NSData *signatureS;
/** Test to see if @c signatureS has been set. */
@property(nonatomic, readwrite) BOOL hasSignatureS;

@end

#pragma mark - EthereumTxAckOneKey

typedef GPB_ENUM(EthereumTxAckOneKey_FieldNumber) {
  EthereumTxAckOneKey_FieldNumber_DataChunk = 1,
};

/**
 * *
 * Request: Transaction payload data.
 * \@next EthereumTxRequestOneKey
 **/
GPB_FINAL @interface EthereumTxAckOneKey : GPBMessage

/** Bytes from transaction payload (<= 1024 bytes) */
@property(nonatomic, readwrite, copy, null_resettable) NSData *dataChunk;
/** Test to see if @c dataChunk has been set. */
@property(nonatomic, readwrite) BOOL hasDataChunk;

@end

#pragma mark - EthereumSignMessageOneKey

typedef GPB_ENUM(EthereumSignMessageOneKey_FieldNumber) {
  EthereumSignMessageOneKey_FieldNumber_AddressNArray = 1,
  EthereumSignMessageOneKey_FieldNumber_Message = 2,
  EthereumSignMessageOneKey_FieldNumber_ChainId = 3,
};

/**
 * *
 * Request: Ask device to sign message
 * \@start
 * \@next EthereumMessageSignatureOneKey
 * \@next Failure
 **/
GPB_FINAL @interface EthereumSignMessageOneKey : GPBMessage

/** BIP-32 path to derive the key from master node */
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *addressNArray;
/** The number of items in @c addressNArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger addressNArray_Count;

/** message to be signed */
@property(nonatomic, readwrite, copy, null_resettable) NSData *message;
/** Test to see if @c message has been set. */
@property(nonatomic, readwrite) BOOL hasMessage;

/** used to personalized display */
@property(nonatomic, readwrite) uint64_t chainId;
@property(nonatomic, readwrite) BOOL hasChainId;

@end

#pragma mark - EthereumMessageSignatureOneKey

typedef GPB_ENUM(EthereumMessageSignatureOneKey_FieldNumber) {
  EthereumMessageSignatureOneKey_FieldNumber_Signature = 2,
  EthereumMessageSignatureOneKey_FieldNumber_Address = 3,
};

/**
 * *
 * Response: Signed message
 * \@end
 **/
GPB_FINAL @interface EthereumMessageSignatureOneKey : GPBMessage

/** signature of the message */
@property(nonatomic, readwrite, copy, null_resettable) NSData *signature;
/** Test to see if @c signature has been set. */
@property(nonatomic, readwrite) BOOL hasSignature;

/** address used to sign the message */
@property(nonatomic, readwrite, copy, null_resettable) NSString *address;
/** Test to see if @c address has been set. */
@property(nonatomic, readwrite) BOOL hasAddress;

@end

#pragma mark - EthereumVerifyMessageOneKey

typedef GPB_ENUM(EthereumVerifyMessageOneKey_FieldNumber) {
  EthereumVerifyMessageOneKey_FieldNumber_Signature = 2,
  EthereumVerifyMessageOneKey_FieldNumber_Message = 3,
  EthereumVerifyMessageOneKey_FieldNumber_Address = 4,
  EthereumVerifyMessageOneKey_FieldNumber_ChainId = 5,
};

/**
 * *
 * Request: Ask device to verify message
 * \@start
 * \@next Success
 * \@next Failure
 **/
GPB_FINAL @interface EthereumVerifyMessageOneKey : GPBMessage

/** signature to verify */
@property(nonatomic, readwrite, copy, null_resettable) NSData *signature;
/** Test to see if @c signature has been set. */
@property(nonatomic, readwrite) BOOL hasSignature;

/** message to verify */
@property(nonatomic, readwrite, copy, null_resettable) NSData *message;
/** Test to see if @c message has been set. */
@property(nonatomic, readwrite) BOOL hasMessage;

/** address to verify */
@property(nonatomic, readwrite, copy, null_resettable) NSString *address;
/** Test to see if @c address has been set. */
@property(nonatomic, readwrite) BOOL hasAddress;

/** used to personalized display */
@property(nonatomic, readwrite) uint64_t chainId;
@property(nonatomic, readwrite) BOOL hasChainId;

@end

#pragma mark - EthereumSignTypedHashOneKey

typedef GPB_ENUM(EthereumSignTypedHashOneKey_FieldNumber) {
  EthereumSignTypedHashOneKey_FieldNumber_AddressNArray = 1,
  EthereumSignTypedHashOneKey_FieldNumber_DomainSeparatorHash = 2,
  EthereumSignTypedHashOneKey_FieldNumber_MessageHash = 3,
  EthereumSignTypedHashOneKey_FieldNumber_ChainId = 4,
};

/**
 * *
 * Request: Ask device to sign hash of typed data
 * \@start
 * \@next EthereumTypedDataSignatureOneKey
 * \@next Failure
 **/
GPB_FINAL @interface EthereumSignTypedHashOneKey : GPBMessage

/** BIP-32 path to derive the key from master node */
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *addressNArray;
/** The number of items in @c addressNArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger addressNArray_Count;

/** Hash of domainSeparator of typed data to be signed */
@property(nonatomic, readwrite, copy, null_resettable) NSData *domainSeparatorHash;
/** Test to see if @c domainSeparatorHash has been set. */
@property(nonatomic, readwrite) BOOL hasDomainSeparatorHash;

/** Hash of the data of typed data to be signed (empty if domain-only data) */
@property(nonatomic, readwrite, copy, null_resettable) NSData *messageHash;
/** Test to see if @c messageHash has been set. */
@property(nonatomic, readwrite) BOOL hasMessageHash;

/** used to personalized display */
@property(nonatomic, readwrite) uint64_t chainId;
@property(nonatomic, readwrite) BOOL hasChainId;

@end

#pragma mark - EthereumTypedDataSignatureOneKey

typedef GPB_ENUM(EthereumTypedDataSignatureOneKey_FieldNumber) {
  EthereumTypedDataSignatureOneKey_FieldNumber_Signature = 1,
  EthereumTypedDataSignatureOneKey_FieldNumber_Address = 2,
};

/**
 * *
 * Response: Signed typed data
 * \@end
 **/
GPB_FINAL @interface EthereumTypedDataSignatureOneKey : GPBMessage

/** signature of the typed data */
@property(nonatomic, readwrite, copy, null_resettable) NSData *signature;
/** Test to see if @c signature has been set. */
@property(nonatomic, readwrite) BOOL hasSignature;

/** address used to sign the typed data */
@property(nonatomic, readwrite, copy, null_resettable) NSString *address;
/** Test to see if @c address has been set. */
@property(nonatomic, readwrite) BOOL hasAddress;

@end

#pragma mark - EthereumSignMessageEIP712

typedef GPB_ENUM(EthereumSignMessageEIP712_FieldNumber) {
  EthereumSignMessageEIP712_FieldNumber_AddressNArray = 1,
  EthereumSignMessageEIP712_FieldNumber_DomainHash = 2,
  EthereumSignMessageEIP712_FieldNumber_MessageHash = 3,
};

/**
 * *
 * Request: Ask device to sign message EIP712
 * \@start
 * \@next EthereumMessageSignature
 * \@next Failure
 **/
GPB_FINAL @interface EthereumSignMessageEIP712 : GPBMessage

/** BIP-32 path to derive the key from master node */
@property(nonatomic, readwrite, strong, null_resettable) GPBUInt32Array *addressNArray;
/** The number of items in @c addressNArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger addressNArray_Count;

/** domainSeparator hash */
@property(nonatomic, readwrite, copy, null_resettable) NSData *domainHash;
/** Test to see if @c domainHash has been set. */
@property(nonatomic, readwrite) BOOL hasDomainHash;

/** message hash */
@property(nonatomic, readwrite, copy, null_resettable) NSData *messageHash;
/** Test to see if @c messageHash has been set. */
@property(nonatomic, readwrite) BOOL hasMessageHash;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
